use std::{path::Path, sync::Arc};

use rmcp::ServiceExt;
use tracing::Instrument;

use crate::{client::HackmdClient, config::Config, local::LocalFiles};

/// MCP server whose handlers share one configured `HackMD` client.
#[derive(Debug, Clone)]
pub(crate) struct HackmdServer {
    client: Arc<HackmdClient>,
    /// Local storage and path policy. The client stays purely about HTTP.
    files: Arc<LocalFiles>,
}

mod account;
mod folder;
mod note;
mod sync;

impl HackmdServer {
    pub(crate) fn new(client: Arc<HackmdClient>, files: Arc<LocalFiles>) -> Self {
        Self { client, files }
    }

    /// The 22 tools, assembled from one router per family. Splitting them keeps
    /// each file about a single part of the API; the router the transport sees
    /// is the same either way.
    ///
    /// Assembled once: dispatch happens per tool call, and rebuilding four
    /// routers to merge them every time is work that never changes.
    fn router() -> &'static rmcp::handler::server::router::tool::ToolRouter<Self> {
        static ROUTER: std::sync::OnceLock<
            rmcp::handler::server::router::tool::ToolRouter<HackmdServer>,
        > = std::sync::OnceLock::new();
        ROUTER.get_or_init(|| {
            Self::account_router()
                + Self::note_router()
                + Self::folder_router()
                + Self::sync_router()
        })
    }
}

pub(crate) async fn run_stdio() -> Result<(), Box<dyn std::error::Error>> {
    let config = Config::from_env()?;
    let files = Arc::new(LocalFiles::new(
        config.state_dir().to_path_buf(),
        config.workspace_root().map(Path::to_path_buf),
    ));
    if let Some(root) = config.workspace_root() {
        tracing::info!(root = %root.display(), "local file tools are confined to this tree");
    }
    let client = Arc::new(HackmdClient::new(config)?);
    if !client.has_api_token() {
        tracing::warn!("HACKMD_API_TOKEN is not set; API tools will return a configuration error");
    }

    HackmdServer::new(client, files)
        .serve(rmcp::transport::stdio())
        .await?
        .waiting()
        .await?;
    Ok(())
}

#[allow(
    clippy::unused_async_trait_impl,
    reason = "the handler bodies are generated by rmcp's tool_handler macro"
)]
#[rmcp::tool_handler(router = Self::router().clone())]
impl rmcp::ServerHandler for HackmdServer {
    /// Wraps every dispatch in one span and one retry scope, so each tool call
    /// carries a request ID through its logs and reports in `_meta` how much
    /// retrying it took.
    async fn call_tool(
        &self,
        request: rmcp::model::CallToolRequestParams,
        context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<rmcp::model::CallToolResponse, rmcp::ErrorData> {
        let request_id = crate::observability::next_request_id();
        let tool_name = request.name.to_string();
        let span = tracing::info_span!(
            "mcp_tool_call",
            request_id = %request_id,
            tool = %tool_name
        );
        let tool_context =
            rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
        async move {
            tracing::info!("tool call started");
            let result = crate::retry::scope_call(Self::router().call(tool_context)).await;
            match &result {
                Ok(rmcp::model::CallToolResponse::Complete(response)) => tracing::info!(
                    is_error = response.is_error.unwrap_or(false),
                    "tool call completed"
                ),
                Ok(_) => tracing::info!("tool call yielded an intermediate response"),
                Err(error) => tracing::warn!(code = ?error.code, "tool call rejected"),
            }
            result
        }
        .instrument(span)
        .await
    }
}

#[cfg(test)]
mod tests {
    /// Local access with no configured root: tool tests exercise the tools, not
    /// the path policy, which has its own tests in `local`.
    fn test_files() -> Arc<crate::local::LocalFiles> {
        Arc::new(crate::fixture::scratch_files())
    }

    use super::HackmdServer;
    use crate::client::HackmdClient;
    use crate::config::Config;
    use crate::server::account::{EmptyInput, profile_result, teams_result};
    use rmcp::{ServerHandler, ServiceExt, model::CallToolRequestParams};
    use serde_json::json;
    use std::sync::Arc;

    const EXPECTED_ANNOTATIONS: [(&str, bool, bool, bool); 24] = [
        ("hackmd_get_me", true, false, true),
        ("hackmd_list_teams", true, false, true),
        ("hackmd_list_notes", true, false, true),
        ("hackmd_get_note", true, false, true),
        ("hackmd_create_note", false, false, false),
        ("hackmd_update_note", false, true, true),
        ("hackmd_delete_note", false, true, true),
        ("hackmd_list_trash", true, false, true),
        ("hackmd_restore_note", false, false, true),
        ("hackmd_edit_note", false, false, false),
        ("hackmd_get_history", true, false, true),
        ("hackmd_list_folders", true, false, true),
        ("hackmd_get_folder", true, false, true),
        ("hackmd_create_folder", false, false, false),
        ("hackmd_update_folder", false, false, true),
        ("hackmd_delete_folder", false, true, true),
        ("hackmd_set_folder_order", false, false, true),
        ("hackmd_upload_note_image", false, false, false),
        ("hackmd_pull_note", false, true, false),
        ("hackmd_push_note", false, true, true),
        ("hackmd_check_note_sync", true, false, true),
        ("hackmd_save_remote_snapshot", false, true, false),
        ("hackmd_list_tracked_notes", true, false, true),
        ("hackmd_untrack_note", false, true, true),
    ];

    async fn protocol_client(
        config: Config,
    ) -> (
        rmcp::service::RunningService<rmcp::RoleClient, ()>,
        tokio::task::JoinHandle<()>,
    ) {
        let (server_transport, client_transport) = tokio::io::duplex(16 * 1024);
        let server = HackmdServer::new(
            Arc::new(HackmdClient::new(config).expect("protocol-test client should build")),
            test_files(),
        );
        let server_task = tokio::spawn(async move {
            server
                .serve(server_transport)
                .await
                .expect("protocol-test server should start")
                .waiting()
                .await
                .expect("protocol-test server task should join");
        });
        let client = ().serve(client_transport).await.expect("RMCP client should connect");
        (client, server_task)
    }

    fn call(name: &'static str, arguments: serde_json::Value) -> CallToolRequestParams {
        let serde_json::Value::Object(arguments) = arguments else {
            panic!("tool arguments should be an object");
        };
        CallToolRequestParams::new(name).with_arguments(arguments)
    }

    async fn stop_protocol(
        client: rmcp::service::RunningService<rmcp::RoleClient, ()>,
        server_task: tokio::task::JoinHandle<()>,
    ) {
        client.cancel().await.expect("RMCP client should cancel");
        server_task.await.expect("protocol-test server should stop");
    }

    #[test]
    fn server_owns_the_shared_client() {
        let client = Arc::new(
            HackmdClient::new(Config::for_tests()).expect("test client should be constructed"),
        );
        let server = HackmdServer::new(Arc::clone(&client), test_files());

        assert_eq!(Arc::strong_count(&client), 2);
        drop(server);
        assert_eq!(Arc::strong_count(&client), 1);
    }

    #[test]
    fn tools_have_generated_schemas_and_exact_annotations() {
        let tools = HackmdServer::router().list_all();

        assert_eq!(tools.len(), 24);
        for (name, read_only, destructive, idempotent) in EXPECTED_ANNOTATIONS {
            let tool = tools
                .iter()
                .find(|tool| tool.name == name)
                .unwrap_or_else(|| panic!("tool {name} should exist"));
            let annotations = tool
                .annotations
                .as_ref()
                .expect("annotations should be generated");
            assert_eq!(annotations.read_only_hint, Some(read_only), "{name}");
            assert_eq!(annotations.destructive_hint, Some(destructive), "{name}");
            assert_eq!(annotations.idempotent_hint, Some(idempotent), "{name}");
            let open_world = !matches!(name, "hackmd_list_tracked_notes" | "hackmd_untrack_note");
            assert_eq!(annotations.open_world_hint, Some(open_world), "{name}");
        }
        for name in ["hackmd_get_me", "hackmd_list_teams"] {
            let tool = tools
                .iter()
                .find(|tool| tool.name == name)
                .expect("discovery tool should exist");
            assert_eq!(tool.input_schema["type"], "object");
            assert_eq!(tool.input_schema["additionalProperties"], false);
        }

        let list = tools
            .iter()
            .find(|tool| tool.name == "hackmd_list_notes")
            .expect("list-notes tool should exist");
        let properties = &list.input_schema["properties"];
        assert_eq!(list.input_schema["additionalProperties"], false);
        assert_eq!(properties["limit"]["default"], 20);
        assert_eq!(properties["limit"]["minimum"], 1);
        assert_eq!(properties["limit"]["maximum"], 100);
        assert_eq!(properties["offset"]["default"], 0);
        assert_eq!(properties["sort"]["default"], "last_changed_desc");
        assert!(properties.get("folder_id").is_none());

        let trash = tools
            .iter()
            .find(|tool| tool.name == "hackmd_list_trash")
            .expect("trash list should exist");
        assert_eq!(trash.input_schema["properties"]["limit"]["default"], 20);
        assert_eq!(trash.input_schema["properties"]["limit"]["maximum"], 100);
        let restore = tools
            .iter()
            .find(|tool| tool.name == "hackmd_restore_note")
            .expect("restore should exist");
        assert_eq!(restore.input_schema["required"], json!(["note_id"]));

        let get_note = tools
            .iter()
            .find(|tool| tool.name == "hackmd_get_note")
            .expect("get-note tool should exist");
        assert_eq!(get_note.input_schema["additionalProperties"], false);
        assert!(
            get_note.input_schema["properties"]
                .get("note_ref")
                .is_some()
        );
        assert_eq!(get_note.input_schema["required"], json!(["note_ref"]));

        for name in [
            "hackmd_create_note",
            "hackmd_update_note",
            "hackmd_delete_note",
            "hackmd_edit_note",
        ] {
            let tool = tools
                .iter()
                .find(|tool| tool.name == name)
                .unwrap_or_else(|| panic!("tool {name} should exist"));
            assert_eq!(tool.input_schema["additionalProperties"], false, "{name}");
        }
        let create = tools
            .iter()
            .find(|tool| tool.name == "hackmd_create_note")
            .expect("create tool should exist");
        for field in [
            "comment_permission",
            "suggest_edit_permission",
            "parent_folder_id",
        ] {
            assert!(create.input_schema["properties"].get(field).is_some());
        }
        let update = tools
            .iter()
            .find(|tool| tool.name == "hackmd_update_note")
            .expect("update tool should exist");
        assert_eq!(update.input_schema["required"], json!(["note_ref"]));
        for field in ["comment_permission", "suggest_edit_permission"] {
            assert!(update.input_schema["properties"].get(field).is_some());
        }
        let edit = tools
            .iter()
            .find(|tool| tool.name == "hackmd_edit_note")
            .expect("edit tool should exist");
        assert_eq!(edit.input_schema["required"], json!(["note_ref", "patch"]));
    }

    #[tokio::test]
    async fn tool_call_reports_actionable_missing_token_error() {
        let server = HackmdServer::new(
            Arc::new(
                HackmdClient::new(Config::for_tests()).expect("test client should be constructed"),
            ),
            test_files(),
        );
        let result = server
            .get_me(rmcp::handler::server::wrapper::Parameters(EmptyInput {}))
            .await;

        assert_eq!(result.is_error, Some(true));
        assert_eq!(
            result.content[0]
                .as_text()
                .expect("error should be text")
                .text,
            "GET /v1/me: HACKMD_API_TOKEN is not configured; set it in the server environment and restart the MCP server"
        );
    }

    #[tokio::test]
    async fn retried_success_and_final_tool_error_include_bounded_metadata() {
        const RETRY_AFTER: &[(&str, &str)] = &[("Retry-After", "0")];
        let retry = crate::config::RetryConfig {
            max_retries: 1,
            initial_backoff: std::time::Duration::from_millis(1),
            max_backoff: std::time::Duration::from_millis(2),
        };
        let success_fixture = crate::fixture::SequenceServer::spawn_with_headers([
            (429, r#"{"error":"rate limited"}"#, RETRY_AFTER),
            (
                200,
                r#"{"id":"u","name":"User","email":"u@example.com","userPath":"user"}"#,
                &[],
            ),
        ]);
        let (client, server_task) = protocol_client(Config::for_loopback_test_with_retry(
            &success_fixture.api_url,
            "fixture-token",
            retry,
        ))
        .await;
        let result = client
            .call_tool(call("hackmd_get_me", json!({})))
            .await
            .expect("retried tool should succeed");
        assert_eq!(result.is_error, Some(false));
        let retry_meta = &result.meta.expect("retried result should have metadata").0["retry"];
        assert_eq!(retry_meta["attempts"], 2);
        assert_eq!(retry_meta["was_rate_limited"], true);
        assert!(
            retry_meta["total_waited_seconds"]
                .as_f64()
                .expect("wait should be numeric")
                <= 0.002
        );
        stop_protocol(client, server_task).await;
        success_fixture.finish();

        let error_fixture = crate::fixture::SequenceServer::spawn([
            (500, r#"{"error":"transient"}"#),
            (500, r#"{"error":"still failing"}"#),
        ]);
        let (client, server_task) = protocol_client(Config::for_loopback_test_with_retry(
            &error_fixture.api_url,
            "fixture-token",
            retry,
        ))
        .await;
        let result = client
            .call_tool(call("hackmd_get_me", json!({})))
            .await
            .expect("tool error should remain a protocol success");
        assert_eq!(result.is_error, Some(true));
        assert_eq!(
            result.meta.expect("final error should have metadata").0["retry"]["attempts"],
            2
        );
        stop_protocol(client, server_task).await;
        error_fixture.finish();
    }

    #[tokio::test]
    async fn update_tool_explains_create_only_permissions() {
        let server = HackmdServer::new(
            Arc::new(
                HackmdClient::new(Config::for_tests()).expect("test client should be constructed"),
            ),
            test_files(),
        );
        let input = serde_json::from_value(json!({
            "note_ref": "id",
            "suggest_edit_permission": "owners"
        }))
        .expect("input should deserialize");
        let result = server
            .update_note(rmcp::handler::server::wrapper::Parameters(input))
            .await;
        assert_eq!(result.is_error, Some(true));
        assert_eq!(
            result.content[0]
                .as_text()
                .expect("error should be text")
                .text,
            "comment_permission and suggest_edit_permission are create-only; HackMD PATCH does not support changing them"
        );
    }

    #[tokio::test]
    async fn edit_conflict_is_a_tool_error_and_never_patches() {
        let fixture = crate::fixture::SequenceServer::spawn([(
            200,
            r#"{"id":"note-id","title":"Title","content":"old"}"#,
        )]);
        let client = fixture.client();
        let server = HackmdServer::new(Arc::new(client), test_files());
        let input = serde_json::from_value(json!({
            "note_ref": "note-id",
            "patch": "*** Begin Patch\n*** Update File: notes/other.md\n@@\n-old\n+new\n*** End Patch"
        }))
        .expect("edit input should deserialize");
        let result = server
            .edit_note(rmcp::handler::server::wrapper::Parameters(input))
            .await;
        assert_eq!(result.is_error, Some(true));
        assert_eq!(
            result.content[0]
                .as_text()
                .expect("error should be text")
                .text,
            "patch targets notes/other.md, expected notes/note-id.md"
        );
        let requests = fixture.finish();
        assert_eq!(requests.len(), 1);
        assert!(requests[0].starts_with("GET /v1/notes/note-id HTTP/1.1\r\n"));
    }

    #[test]
    fn discovery_results_preserve_resolution_paths() {
        let profile = serde_json::from_value(json!({
            "id": "user-id",
            "name": "Alice",
            "email": "alice@example.test",
            "userPath": "alice",
            "photo": null,
            "teams": []
        }))
        .expect("profile fixture should deserialize");
        let profile_result = profile_result(&profile);
        assert_eq!(
            profile_result.structured_content,
            Some(json!({
                "profile": {
                    "id": "user-id",
                    "name": "Alice",
                    "email": "alice@example.test",
                    "userPath": "alice",
                    "photo": null,
                    "teams": []
                }
            }))
        );

        let teams: Vec<crate::dto::TeamResponse> = serde_json::from_value(json!([{
            "id": "team-id",
            "name": "Engineering",
            "path": "engineering",
            "description": null,
            "hardLimit": 100,
            "visibility": "private"
        }]))
        .expect("team fixture should deserialize");
        let teams_result = teams_result(&teams);
        assert_eq!(
            teams_result
                .structured_content
                .as_ref()
                .expect("structured teams")["teams"][0]["path"],
            "engineering"
        );
    }

    #[test]
    fn server_handler_enables_tools_only() {
        let client =
            HackmdClient::new(Config::for_tests()).expect("test client should be constructed");
        let info = HackmdServer::new(Arc::new(client), test_files()).get_info();

        assert!(info.capabilities.tools.is_some());
        assert!(info.capabilities.prompts.is_none());
        assert!(info.capabilities.resources.is_none());
    }

    #[tokio::test]
    async fn in_process_tools_list_exposes_generated_contract() {
        let (client, server_task) = protocol_client(Config::for_tests()).await;
        let listed = client
            .list_tools(None)
            .await
            .expect("tools/list should succeed");
        assert_eq!(listed.tools.len(), 24);
        for (name, read_only, destructive, idempotent) in EXPECTED_ANNOTATIONS {
            let tool = listed
                .tools
                .iter()
                .find(|tool| tool.name == name)
                .unwrap_or_else(|| panic!("tools/list omitted {name}"));
            let annotations = tool.annotations.as_ref().expect("annotations should exist");
            assert_eq!(annotations.read_only_hint, Some(read_only), "{name}");
            assert_eq!(annotations.destructive_hint, Some(destructive), "{name}");
            assert_eq!(annotations.idempotent_hint, Some(idempotent), "{name}");
        }
        let edit = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_edit_note")
            .expect("edit tool should be listed");
        assert_eq!(edit.input_schema["required"], json!(["note_ref", "patch"]));
        let annotations = edit.annotations.as_ref().expect("annotations should exist");
        assert_eq!(annotations.read_only_hint, Some(false));
        assert_eq!(annotations.destructive_hint, Some(false));
        assert_eq!(annotations.idempotent_hint, Some(false));
        let list = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_list_notes")
            .expect("list tool should be listed");
        assert_eq!(list.input_schema["properties"]["limit"]["default"], 20);
        assert_eq!(list.input_schema["properties"]["limit"]["maximum"], 100);
        let update = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_update_note")
            .expect("update tool should be listed");
        assert_eq!(update.input_schema["required"], json!(["note_ref"]));
        assert!(
            update.input_schema["properties"]
                .get("comment_permission")
                .is_some()
        );
        let history = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_get_history")
            .expect("history tool should be listed");
        assert_eq!(history.input_schema["properties"]["limit"]["default"], 20);
        assert_eq!(history.input_schema["properties"]["limit"]["maximum"], 100);
        let pull = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_pull_note")
            .expect("pull tool should be listed");
        assert_eq!(pull.input_schema["additionalProperties"], false);
        assert_eq!(
            pull.input_schema["required"],
            json!(["note_ref", "local_path"])
        );
        assert_eq!(
            pull.input_schema["properties"]["overwrite_local"]["default"],
            false
        );
        assert_eq!(
            pull.input_schema["properties"]["create_parent_dirs"]["default"],
            false
        );
        let push = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_push_note")
            .expect("push tool should be listed");
        assert_eq!(push.input_schema["additionalProperties"], false);
        assert_eq!(
            push.input_schema["required"],
            json!(["note_ref", "local_path"])
        );
        assert_eq!(
            push.input_schema["properties"]["strategy"]["default"],
            "safe"
        );
        assert_eq!(push.input_schema["properties"]["confirm"]["default"], false);
        let tracked = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_list_tracked_notes")
            .expect("tracked-note list should be listed");
        assert_eq!(tracked.input_schema["properties"]["limit"]["default"], 20);
        assert_eq!(tracked.input_schema["properties"]["limit"]["maximum"], 100);
        assert_eq!(tracked.input_schema["properties"]["offset"]["default"], 0);
        let untrack = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_untrack_note")
            .expect("untrack tool should be listed");
        assert_eq!(untrack.input_schema["required"], json!(["note_id"]));
        assert_eq!(
            untrack.input_schema["properties"]["confirm"]["default"],
            false
        );
        let folders = listed
            .tools
            .iter()
            .find(|tool| tool.name == "hackmd_list_folders")
            .expect("folder list should be listed");
        assert_eq!(folders.input_schema["properties"]["limit"]["default"], 20);
        assert_eq!(folders.input_schema["properties"]["limit"]["maximum"], 100);
        assert_eq!(folders.input_schema["properties"]["offset"]["default"], 0);
        stop_protocol(client, server_task).await;
    }

    #[tokio::test]
    async fn in_process_list_call_covers_team_route_search_and_pagination() {
        let fixture = crate::fixture::SequenceServer::spawn([(
            200,
            r#"[
                {"id":"a","title":"Roadmap A","description":"Rust work","tags":["rust"],"lastChangedAt":3},
                {"id":"b","title":"Roadmap B","description":"Rust work","tags":["RUST"],"lastChangedAt":2},
                {"id":"c","title":"Other","description":"Rust work","tags":["rust"],"lastChangedAt":1}
            ]"#,
        )]);
        let (client, server_task) = protocol_client(Config::for_loopback_test(
            &fixture.api_url,
            Some("fixture-token"),
        ))
        .await;
        let result = client
            .call_tool(call(
                "hackmd_list_notes",
                json!({
                    "workspace": {"kind": "team", "team_path": "core/team"},
                    "query": "ROADMAP",
                    "tags": ["rust"],
                    "limit": 1,
                    "offset": 1
                }),
            ))
            .await
            .expect("tools/call should succeed");
        assert_eq!(result.is_error, Some(false));
        let structured = result
            .structured_content
            .expect("structured result should exist");
        assert_eq!(structured["total"], 2);
        assert_eq!(structured["count"], 1);
        assert_eq!(structured["offset"], 1);
        assert_eq!(structured["has_more"], false);
        assert_eq!(structured["notes"][0]["id"], "b");
        stop_protocol(client, server_task).await;
        let requests = fixture.finish();
        assert_eq!(requests.len(), 1);
        assert!(requests[0].starts_with("GET /v1/teams/core%2Fteam/notes HTTP/1.1\r\n"));
    }

    #[tokio::test]
    async fn in_process_edit_calls_cover_no_op_and_conflict_without_patch() {
        let fixture = crate::fixture::SequenceServer::spawn([
            (200, r#"{"id":"same","title":"Same","content":"same"}"#),
            (
                200,
                r#"{"id":"conflict","title":"Conflict","content":"actual"}"#,
            ),
        ]);
        let (client, server_task) = protocol_client(Config::for_loopback_test(
            &fixture.api_url,
            Some("fixture-token"),
        ))
        .await;
        let no_op = client
            .call_tool(call(
                "hackmd_edit_note",
                json!({
                    "note_ref": "same",
                    "patch": "*** Begin Patch\n*** Update File: notes/same.md\n@@\n same\n*** End Patch"
                }),
            ))
            .await
            .expect("no-op tool call should succeed");
        assert_eq!(no_op.is_error, Some(false));
        assert_eq!(
            no_op.structured_content.expect("no-op result")["result"]["changed"],
            false
        );

        let conflict = client
            .call_tool(call(
                "hackmd_edit_note",
                json!({
                    "note_ref": "conflict",
                    "patch": "*** Begin Patch\n*** Update File: notes/conflict.md\n@@\n-missing\n+new\n*** End Patch"
                }),
            ))
            .await
            .expect("conflict tool call should return a tool result");
        assert_eq!(conflict.is_error, Some(true));
        assert_eq!(
            conflict.content[0]
                .as_text()
                .expect("conflict should be text")
                .text,
            "patch hunk context was not found"
        );
        stop_protocol(client, server_task).await;
        let requests = fixture.finish();
        assert_eq!(requests.len(), 2);
        assert!(requests[0].starts_with("GET /v1/notes/same HTTP/1.1\r\n"));
        assert!(requests[1].starts_with("GET /v1/notes/conflict HTTP/1.1\r\n"));
    }
}
